### ISSUE TITLE
Investigate missing asyncio support for Celery

### ISSUE THREAD

**Issue by devraj** [anomaly/lab-python-server#21]
As part of this lab, we made a massive push to migrate our technology stack including the future of SQLAlchemy which is headed towards a 2.0 syntax (this is in line with SQLAlchemy 2.0 release, where there 1.4 branch provides a migration strategy). This aligns SQLAlchemy to work with the async mode that our `asgi` application based on FastAPI was already headed.

Celery our queue processor of choice was meant to support `ayncio` in the `5.x` release, which is what we use in this stack. Until such time that Celery supports we have the following choices:

- Use FastAPI background tasks wherever possible to process background tasks
- Find a way to use `async` code in a `sync` fashion so we can use Celery without `asyncio` support 
- Provide a `sync` version of SQLAlchemy sessions and queries - this is the least preferred option as it will add unwanted code that will significantly add to the technical debt

At the moment our use cases for applications would be able to get away with using FastAPI background tasks, our current requirements are limited to sending SMS and email and processing `webhook` payloads from `Stripe` (these could take longer depending on what we are trying to do and would be more suited to `Celery` handled tasks).

**Comment by devraj** [comment]
[kai3341/celery-pool-asyncio](https://github.com/kai3341/celery-pool-asyncio) seems to have a viable solution that might be worth trying to see if we can get a solution running until Celery officially supports `asyncio`

**Comment by devraj** [comment]
The above commit breaks the `main` branch, on inspection I found [celery-decorator-taskcls-example](https://github.com/kai3341/celery-decorator-taskcls-example) which has a demonstration of how to use `asyncio` package with Celery - follow the `celery-asyncio` branch for progress on this work.

If the attempt fails then `main` will be returned to it's original state and we will try different approaches until `Celery` officially supports `asyncio`

**Comment by devraj** [comment]
Follow [this thread](https://github.com/celery/celery/issues/3884) for commentary on using the third party project and [code sample](https://github.com/codesutras/celery-pool-asyncio-example).

Also discussing with project maintainers in being able to sponsor the work to get it over the line.

**Comment by auvipy** [comment]
hello O:)

**Comment by devraj** [comment]
@auvipy sorry I didn't see this earlier, have been on another projects for a while. Please [email me](https://www.anomaly.ltd/contact) and we can converse there.

**Comment by devraj** [comment]
Not quite a solution but I have managed to use the `async` handlers in `sync` mode to get by for now:

```
"""Email related tasks

"""

import asyncio
from sqlalchemy.ext.asyncio import AsyncSession

from ...celery import app
from ...db import get_async_session
from ...models import Customer

# Globally available loop to run async tasks
loop = asyncio.get_event_loop()

async def get_user():
    session_generator = get_async_session()
    session = await session_generator.asend(None)
    import logging
    customers = await Customer.get_all(session)
    logging.error(customers)

@app.task(ignore_result=True)
def verification_email():
    loop.run_until_complete(get_user())
```

Import note to read the [Async generator docs](https://peps.python.org/pep-0525/#asynchronous-generator-object) and how the `session_generator.asend(None)` gets the `AsyncSession` object.

I will post a.  more defined version of this as I make progress and merge it into the codebase.

**Comment by devraj** [comment]
@tiangolo maintains [Asyncify](https://asyncer.tiangolo.com) a utility to assist with cleanly mixing `sync` and `async`, while the above code sample is enough to run our `async` code in the `sync` code, it might be cleaner to adopt the library to see the migration of `Celery` through to `asyncio`

**Comment by auvipy** [comment]
that is a good stuff,, also asgiref provide async_to_sync and sync_to_async utility as well which need to be investigated as well

**Comment by devraj** [comment]
I am considering other alternatives as I don't think this is going to move in a positive direction soon.

Came across [TaskIQ](https://taskiq-python.github.io/) which features [FastAPI](https://taskiq-python.github.io/guide/taskiq-with-fastapi.html) integration and `asyncio`, we should investigate using this.

Thanks @s3rius and other maintainers. 

Note also see [FastAPI template](https://github.com/s3rius/FastAPI-template) which has similarities to this project.

**Comment by s3rius** [comment]
Hi, @devraj, we're glad you found our project. If you're going to use taskiq, we're always here to help.  

Also, don't forget to hit the star button and describe your experience in this [discussion](https://github.com/orgs/taskiq-python/discussions/69).
