### ISSUE TITLE
Consider turning this repository into a `remix-stack`

### ISSUE THREAD

**Issue by devraj** [anomaly/lab-python-server#70]
**Is your feature request related to a problem? Please describe.**
Remix [stacks](https://remix.run/docs/en/dev/pages/stacks) are meant to be a software stack that incorporate the Remix application into it. They are meant to provide a standardised way implementations of:

- Database
- Automatic deployment pipelines
- Authentication
- Testing
- Linting/Formatting/TypeScript

The above is the problem we are trying to solve for Anomaly via these labs.

**Describe the solution you'd like**
If this [breaking change](https://github.com/anomaly/lab-web-client/issues/24) deems that Remix is the suitable production framework (since we already use react router) then we:
- rename this to become a Remix stack
- make the `web-client` redundant
- all Anomaly apps boot up as a `remix-stack` with our preferred server side frameworks

This also fundamentally changes the way we are managing repositories for Anomaly projects, combining the server and client side workflows into the single repository.

There is possibly a use case where we archive the current lab repositories and the work that was done in them and create a separate repository for `psychedelic-stack`

**Describe alternatives you've considered**

For as long as I have maintained this repository, I have been trying to standardise the client side and maintained a [template here](https://github.com/anomaly/lab-web-client/). There have been many changes to frameworks like NextJS and Remix since the introduction of React 18 (which had some fundamental improvement).

This lead to standardisation of production framework with unified set of features like routing, caching, header management, which would mean that we can give up tracking many individual projects and take a more wholistic approach. 

This would be a [breaking change](https://github.com/anomaly/lab-web-client/issues/24) and would mean that the client project be unified into this repository.

**Additional context**
`remix` recommend you name your stacks after a musical sub-genre. Proposed name for the stack be `psychedelic-stack` where `p` presents `python` and the musical sub-genre honours `Pink Floyd`.

**Comment by devraj** [comment]
## Thoughts on SSL for development

[create-react-app](https://create-react-app.dev/docs/using-https-in-development/) support SSL for development and we have been using this as part of the [lab-web-client](https://github.com/anomaly/lab-web-client), moving to `remix` means that there's no native support for SSL.

There are some documented [workarounds](https://medium.com/@dogukanakkaya/local-https-express-server-with-remix-framework-f7723c657066) where we configure the `express` server. This also applies for [proxying](https://github.com/remix-run/remix/discussions/2971) the `api` endpoints from the `docker` container (something that `create-react-app` lets us do also).

The broader discussion here is what `anomaly` deems to be the stack going forward.

The aim of these `labs` has been to create a stack that is _agnostic_ of any deployment targets i.e as open as possible so we can choose a infrastructure provider.

`Remix` templates provide the option of pre-configuring the project to be run in environments like `Netlify` or `Vercel` something that Anomaly does use to deploy say their web site.

If we were to choose `netlify` as the front end host, then:
- we can run [SSL](https://github.com/netlify/cli/pull/2132) via their [command line tools](https://cli.netlify.com/netlify-dev/#running-an-https-server-for-local-development)
- [proxy](https://docs.netlify.com/routing/redirects/rewrites-proxies/) the api endpoints via their command line tools

There's also a [follow up ticket](https://github.com/netlify/cli/issues/2136) for the cli tools to autogenerate the SSL certificates which would take away another function from our templates.

> Read this blog post about [Remix and Netlify cli](https://www.netlify.com/blog/how-to-deploy-remix-apps-on-netlify/)

This approach would mean that the stack will depend on Netlify for all projects. While it's noted that `remix` allows for the deployment target to be changed, it would see there [are some gotchas](https://stephenweiss.dev/remix-how-to-update-your-server-target).

The question remains as to how much we build upon what Netlify is doing or do we want to stay completely agnostic of providers?

> It is also noted that we are using Remix as a [Backend for our Frontend](https://remix.run/docs/en/main/guides/bff) and not buying into the complete stack, as our Python based server framework is preferred.

**Comment by devraj** [comment]
Adding the following achieves SSL and proxying the API to the container.
```toml
[dev]
  command = "remix watch"
  port = 3000
  [dev.https]
    certFile = ".cert/cert.pem"
    keyFile = ".cert/key.pem"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/:splat"
  status = 200
  headers = {X-From = "Netlify"}
```

Once we decide where to store the remix applicaiton (in this repository or another), we can make a decision on if we run the netlify cli inside of a container (taking away the need to run a separate process in another window).

We have to make a decision as to what a deployed version looks like specially on a fully managed version e.g on AWS.

**Comment by devraj** [comment]
When I use the `ntl dev` development server, the app throws hydration `exceptions` complaining that the app state is different to that of what's on the server.

Initially I went down the rabbit hold where developers are talking about [hydration issues](https://github.com/Xiphe/remix-island) caused by `react18` and workarounds until `18.3` fixes this.

Eventually I ran the `ntl dev` with and without `TLS` and then ran `yarn dev` to find that the app works when using the `remix` server but not when being served via `ntl dev`. I also [found this](https://github.com/remix-run/remix/pull/3754) where @nickytonline from @netlify is attempting to fix the developer experience of the `netlify` template.

My hypothesis is that the `netlify` server is injecting something in the response which makes the app drift from the server state. 

<img width="1552" alt="Screenshot 2023-04-29 at 3 55 29 pm" src="https://user-images.githubusercontent.com/5961/235286418-e9d94d04-a104-4fac-8b2f-d7b30699b96c.png">

**Comment by devraj** [comment]
Thought I would check on the @vercel if I can use their `cli` tools:
- SSL is possible but [not supported out of the box](https://github.com/vercel/vercel/discussions/5114) - not a show stopper but would be nice to have
- Proxying is [not supported at the moment](https://github.com/vercel/vercel/discussions/4752)
- Hot reloading works ✅

**Comment by devraj** [comment]
Following on my discussion on the PR on the `remix` repository, it turns out that the maintained template lives at https://github.com/netlify/remix-template and hence creating a remix app via

```
npx create-remix@latest --template https://github.com/netlify/remix-template test
```

does the trick and everything works.

It's suggested at this point that we restart the stack with this template for `Netlify` hosted projects.

**Comment by nickytonline** [comment]
Glad to see it's working @devraj!

**Comment by devraj** [comment]
Hey @nickytonline, I am chasing my tail to figure the browser would loose the websocket connection for live reload when I am running `ntl dev`. My setup is 

- Project bootstrapped via the netlify template for remix
- SSL configured to run locally, with a little help from [mkcert](https://github.com/FiloSottile/mkcert)
- Proxy `/api` to a docker container running a Python application

I am not seeing something that's [defined in this issue here](https://github.com/remix-run/remix/issues/2958) and have lost the ability to live reload when going the netlify server + https.

If I hit the app at port `3000` all works well.

The issue lodged on `remix` suggests that adding `devServerPort` in the remix configuration should work but that does not seem to make a difference.

If you have any thoughts on this I would appreicate a comment. 🙏

My current efforts are in [this repository](https://github.com/anomaly/psychedelic-stack/)

**Comment by devraj** [comment]
Please track the issue on @remix-run/remix [LiveReload doesn't work when TLS is enabled](https://github.com/remix-run/remix/issues/2859) for a discussion on this exact same pending issue on Websockets not working when TLS is enabled.

**Comment by devraj** [comment]
See [this discussion](https://github.com/netlify/remix-template/discussions/122) which reveals that we have to import from the `deno` runtime if we want to execute `remix` on netlify `edge` functions
